apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digital-banking-app
  template:
    metadata:
      labels:
        app: digital-banking-app
    spec:
      # SonarQube Fix: Disable automounting service account token for security
      automountServiceAccountToken: false 
      containers:
      - name: digital-banking-app
        image: abithanisha/digital-banking-app:v1 # 'latest' tag vendam, v1 nu kudunga
        ports:
        - containerPort: 3000
        # SonarQube Fix: Added Resource Requests and Limits
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: digital-banking-app-service
spec:
  type: NodePort
  selector:
    app: digital-banking-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
