apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digital-banking-app
  template:
    metadata:
      labels:
        app: digital-banking-app
    spec:
      automountServiceAccountToken: false 
      containers:
      - name: digital-banking-app
        image: abithanisha/digital-banking-app:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
            ephemeral-storage: "64Mi"  # <--- Ithu thaan SonarQube keta fix
          limits:
            memory: "128Mi"
            cpu: "500m"
            ephemeral-storage: "128Mi" # <--- Ithu thaan SonarQube keta fix
---
apiVersion: v1
kind: Service
metadata:
  name: digital-banking-app-service
spec:
  type: NodePort
  selector:
    app: digital-banking-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
